// AUTO-GENERATED — do not edit by hand.
// Run: python scripts/generate_pipeline_types.py

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PipelineTypes = PipelineBlock | PipelineCondition | SwitchBranchSchema;
export type PipelineBlock =
  | KeywordFilterSchema
  | SemanticSimilaritySchema
  | LLMFilterSchema
  | RegexFilterSchema
  | ConditionalSchema
  | SwitchSchema
  | CustomBlockSchema;
export type Type = "keyword_filter";
export type Include = string[];
export type Exclude = string[];
export type Type1 = "semantic_similarity";
export type Query = string;
export type Field = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Threshold = number;
export type EmbeddingModel = string;
export type Type2 = "llm_filter";
export type Prompt = string;
export type Tier = "mini" | "medium" | "high";
export type BatchPrompt = string | null;
export type BatchSize = number;
export type Type3 = "regex_filter";
export type Field1 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Pattern = string;
export type Mode = "include" | "exclude";
export type Type4 = "conditional";
export type Condition =
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema;
export type Type5 = "and";
export type Type6 = "or";
export type Type7 = "not";
export type Condition1 =
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema;
export type Type8 = "source_type";
export type Value = "rss" | "reddit" | "youtube" | "nitter" | "google_news" | "tavily";
export type Type9 = "source_name";
export type Value1 = string;
export type Type10 = "source_url";
export type Value2 = string;
export type Type11 = "domain";
export type Value3 = string;
export type Type12 = "source_domain";
export type Value4 = string;
export type Type13 = "field_equals";
export type Field2 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Value5 = string;
export type Type14 = "field_contains";
export type Field3 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Value6 = string;
export type Type15 = "field_exists";
export type Field4 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Type16 = "field_matches_regex";
export type Field5 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Pattern1 = string;
export type Type17 = "keyword";
export type Terms = string[];
export type Operator = "any" | "all";
export type Type18 = "length";
export type Field6 = "title" | "content" | "full_text" | "source_name" | "source_type" | "url" | "published_at";
export type Min = number;
export type Max = number;
export type Type19 = "published_after";
export type DaysAgo = number;
export type Type20 = "published_before";
export type DaysAgo1 = number;
export type Type21 = "llm";
export type Prompt1 = string;
export type Tier1 = "mini" | "medium" | "high";
export type Conditions1 = (
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema
)[];
export type Conditions = (
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema
)[];
export type Type22 = "switch";
export type Condition2 =
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema;
export type Type23 = "custom_block";
export type Name = string;
export type Blocks = (
  | KeywordFilterSchema
  | SemanticSimilaritySchema
  | LLMFilterSchema
  | RegexFilterSchema
  | ConditionalSchema
  | SwitchSchema
  | CustomBlockSchema
)[];
export type Branches = SwitchBranchSchema[];
export type Default = (
  | KeywordFilterSchema
  | SemanticSimilaritySchema
  | LLMFilterSchema
  | RegexFilterSchema
  | ConditionalSchema
  | SwitchSchema
  | CustomBlockSchema
)[];
export type IfTrue = (
  | KeywordFilterSchema
  | SemanticSimilaritySchema
  | LLMFilterSchema
  | RegexFilterSchema
  | ConditionalSchema
  | SwitchSchema
  | CustomBlockSchema
)[];
export type IfFalse = (
  | KeywordFilterSchema
  | SemanticSimilaritySchema
  | LLMFilterSchema
  | RegexFilterSchema
  | ConditionalSchema
  | SwitchSchema
  | CustomBlockSchema
)[];
export type PipelineCondition =
  | AndConditionSchema
  | OrConditionSchema
  | NotConditionSchema
  | SourceTypeConditionSchema
  | SourceNameConditionSchema
  | SourceUrlConditionSchema
  | DomainConditionSchema
  | SourceDomainConditionSchema
  | FieldEqualsConditionSchema
  | FieldContainsConditionSchema
  | FieldExistsConditionSchema
  | FieldMatchesRegexConditionSchema
  | KeywordConditionSchema
  | LengthConditionSchema
  | PublishedAfterConditionSchema
  | PublishedBeforeConditionSchema
  | LLMConditionSchema;

export interface KeywordFilterSchema {
  type: Type;
  include?: Include;
  exclude?: Exclude;
}
export interface SemanticSimilaritySchema {
  type: Type1;
  query: Query;
  field: Field;
  threshold?: Threshold;
  embedding_model?: EmbeddingModel;
}
export interface LLMFilterSchema {
  type: Type2;
  prompt: Prompt;
  tier?: Tier;
  batch_prompt?: BatchPrompt;
  batch_size?: BatchSize;
}
export interface RegexFilterSchema {
  type: Type3;
  field: Field1;
  pattern: Pattern;
  mode?: Mode;
}
export interface ConditionalSchema {
  type: Type4;
  condition: Condition;
  if_true?: IfTrue;
  if_false?: IfFalse;
}
export interface AndConditionSchema {
  type: Type5;
  conditions: Conditions;
}
export interface OrConditionSchema {
  type: Type6;
  conditions: Conditions1;
}
export interface NotConditionSchema {
  type: Type7;
  condition: Condition1;
}
export interface SourceTypeConditionSchema {
  type: Type8;
  value: Value;
}
export interface SourceNameConditionSchema {
  type: Type9;
  value: Value1;
}
export interface SourceUrlConditionSchema {
  type: Type10;
  value: Value2;
}
export interface DomainConditionSchema {
  type: Type11;
  value: Value3;
}
export interface SourceDomainConditionSchema {
  type: Type12;
  value: Value4;
}
export interface FieldEqualsConditionSchema {
  type: Type13;
  field: Field2;
  value: Value5;
}
export interface FieldContainsConditionSchema {
  type: Type14;
  field: Field3;
  value: Value6;
}
export interface FieldExistsConditionSchema {
  type: Type15;
  field: Field4;
}
export interface FieldMatchesRegexConditionSchema {
  type: Type16;
  field: Field5;
  pattern: Pattern1;
}
export interface KeywordConditionSchema {
  type: Type17;
  terms: Terms;
  operator: Operator;
}
export interface LengthConditionSchema {
  type: Type18;
  field: Field6;
  min: Min;
  max: Max;
}
export interface PublishedAfterConditionSchema {
  type: Type19;
  days_ago: DaysAgo;
}
export interface PublishedBeforeConditionSchema {
  type: Type20;
  days_ago: DaysAgo1;
}
export interface LLMConditionSchema {
  type: Type21;
  prompt: Prompt1;
  tier?: Tier1;
}
export interface SwitchSchema {
  type: Type22;
  branches: Branches;
  default?: Default;
}
export interface SwitchBranchSchema {
  condition: Condition2;
  blocks?: Blocks;
}
export interface CustomBlockSchema {
  type: Type23;
  name: Name;
}


export const PIPELINE_ARTICLE_FIELDS = ["title", "content", "full_text", "source_name", "source_type", "url", "published_at"] as const;
export const PIPELINE_SOURCE_TYPE_VALUES = ["rss", "reddit", "youtube", "nitter", "google_news", "tavily"] as const;
